services:
  django:
    networks:
      - ftt
    build:
      context: srcs/backend
      dockerfile: "Dockerfile"
    ports:
      - "8000:8000"
    restart: unless-stopped

networks:
  ftt:
    driver: bridge