services:
  nginx:
    networks:
      - ftt
    build:
      context: srcs/
      dockerfile: "nginx/Dockerfile"
    ports:
      - "8080:80"
    restart: unless-stopped

  django:
    networks:
      - ftt
    build:
      context: srcs/backend
      dockerfile: "Dockerfile"
    ports:
      - "8000:8000"
    # restart: unless-stopped

networks:
  ftt:
    driver: bridge