services:
  nginx:
    networks:
      - ftt
    build:
      context: srcs/
      dockerfile: "nginx/Dockerfile"
    ports:
      - "8080:8080"
    depends_on:
      - django
    restart: unless-stopped

  django:
    networks:
      - ftt
    build:
      context: srcs/backend
      dockerfile: "Dockerfile"
    restart: unless-stopped

networks:
  ftt:
    driver: bridge