services:
  # django:
  #   networks:
  #     - ftt
  #   build:
  #     context: srcs/backend
  #     dockerfile: "Dockerfile"
  #   ports:
  #     - "8000:8000"
  #   restart: unless-stopped
  
  vault:
    networks:
      - ftt
    build:
      context: srcs/vault
      dockerfile: "Dockerfile"
    ports:
      - "8200:8200"
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: on-failure

networks:
  ftt:
    driver: bridge